[package]
name = "evox2-control"
version = "2.4.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "evox2-control"
path = "src/main.rs"
test = false

[dependencies]
winapi = { version = "0.3", features = ["winnt", "winerror", "handleapi", "fileapi", "ioapiset", "minwinbase", "errhandlingapi", "winbase", "processthreadsapi", "securitybaseapi", "winuser", "consoleapi", "processenv", "synchapi", "winreg", "wincon", "shellapi", "libloaderapi", "commdlg", "winnls", "stringapiset", "sysinfoapi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
egui = "0.34.3"
eframe = { version = "0.34.3", default-features = false, features = [
    "default_fonts",
    "glow",
] }
image = "0.25"
raw-window-handle = "0.6.2"

[build-dependencies]
winres = "0.1"
